apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  labels:
    app: nginx-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: gpt-researcher
        image: gcr.io/gptserchai/github.com/jlcases/gpt-researcher:8b9f855d860deeb8ba0f30e93cf10f1a9a1575f4
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
